# Generated by Django 5.1 on 2024-09-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='Id',
            field=models.IntegerField(default=0),
        ),
    ]
