# Generated by Django 5.1 on 2024-09-17 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_jobs_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='Id',
        ),
    ]
